In [16]:
#import required libs
import pandas as pd
from geopy.geocoders import Nominatim

In [17]:
#district list
url = 'https://api.covid19india.org/csv/latest/district_list.csv'

#initialize Nominatim geocoder
geolocator = Nominatim(user_agent="your_agent") #replace your_agent

#set country for accurate results
country ="India"

#load the district list into df
df = pd.read_csv(url)
df.head()

,N,District,State,Notes
0,1,Nicobars,Andaman and Nicobar Islands,NaN
1,2,North and Middle Andaman,Andaman and Nicobar Islands,NaN
2,3,South Andaman,Andaman and Nicobar Islands,Port Blair is in South Andaman
3,4,Anantapur,Andhra Pradesh,NaN
4,5,Chittoor,Andhra Pradesh,NaN

In [18]:
#create a new dataframe to hold result
new_df = pd.DataFrame( columns =['District', 'State', 'Latitude', 'Longitude'])

In [19]:
for district,state in zip(df['District'],df['State']):
    
    try:
        
        #build the query
        loc = geolocator.geocode(district+', '+state+', '+ country)
        
        #print('\nLOCATION FOUND\n'+district+', '+state,'\n',loc.latitude,',',loc.longitude)
        
        #store the incoming data inside a dict.
        data = { 'District': district, 'State':state, 'Latitude': loc.latitude, 'Longitude': loc.longitude }
        
        #append the dict. to new_df
        new_df=new_df.append(data,ignore_index=True,sort=False)
                                            
        
    except:  
        
        #print when location not found
        print("\nLOCATION NOT FOUND\n"+district+', '+state)

LOCATION NOT FOUND
Nicobars, Andaman and Nicobar Islands

LOCATION NOT FOUND
S.P.S. Nellore, Andhra Pradesh

LOCATION NOT FOUND
Bametara, Chhattisgarh

LOCATION NOT FOUND
Dakshin Bastar Dantewada, Chhattisgarh

LOCATION NOT FOUND
Kabeerdham, Chhattisgarh

LOCATION NOT FOUND
Mirpur, Jammu and Kashmir

LOCATION NOT FOUND
Muzaffarabad, Jammu and Kashmir

LOCATION NOT FOUND
Shopiyan, Jammu and Kashmir

LOCATION NOT FOUND
Ribhoi, Meghalaya

LOCATION NOT FOUND
Shahid Bhagat Singh Nagar, Punjab

LOCATION NOT FOUND
Komaram Bheem, Telangana

LOCATION NOT FOUND
Sipahijala, Tripura

LOCATION NOT FOUND
Shrawasti, Uttar Pradesh

LOCATION NOT FOUND
Siddharthnagar, Uttar Pradesh

In [20]:
#save the df to csv
new_df.to_csv('coordinates.csv')

In [22]:
#preview the result
df = pd.read_csv('coordinates.csv')
df.head()

,Unnamed: 0,District,State,Latitude,Longitude
0,0,North and Middle Andaman,Andaman and Nicobar Islands,12.611239,92.831654
1,1,South Andaman,Andaman and Nicobar Islands,10.705690,92.487468
2,2,Anantapur,Andhra Pradesh,14.654623,77.556260
3,3,Chittoor,Andhra Pradesh,13.160105,79.155551
4,4,East Godavari,Andhra Pradesh,17.233496,81.722599